### ISSUE TITLE
Cross Platform support

### ISSUE THREAD

**Issue by arnav127** [kivi3004/Snake-Game#1]
Currently this program only works on WIndows, I want to add cross platform support so it can run on Linux also.   
I plan to do this by detecting the operating system by `#ifdef` macros, this will help to include os dependent files and the same code can be compiled on both Linux and WIndows.

**Comment by kivi3004** [comment]
Yeah! I know that my program is specified only for Windows.
Currently I don't have any experience about Linux thats why I can't add your changes in my program from my side.
